#!/usr/bin/env python

"""
Main program for audiobook-reencoder

calls the functions in audiobook_tools/audiobook_reencoder/audiobook_reencoder.py
"""

if __name__ == "__main__" :
    from audiobook_tools.audiobook_reencoder import audiobook_reencoder
    audiobook_reencoder.main()   
