#!/usr/bin/env python

"""
Main program for web-novel-to-text

calls the functions in audiobook_tools/web_novel_to_text/web_novel_to_text.py
"""


# use pretty-errors, if its installed
try:
    import pretty_errors
except:
    pass

if __name__ == "__main__":
    from audiobook_tools.web_novel_to_text import web_novel_to_text
    web_novel_to_text.main()
