#!/usr/bin/env python

"""
Main program for online-tts

calls the functions in audiobook_tools/online_tts/online_tts.py
"""

if __name__ == "__main__" :
    from audiobook_tools.online_tts import online_tts
    online_tts.main()   